import Head from "next/head";
import Image from "next/image";
import styles from "@/styles/Home.module.css";
import { Fragment, useState } from "react";
import AccordionItem from "../components/accordion-item";


export default function Home() {

  const [isOpen, setIsOpen] = useState({
    Expertise: false,
    People: false,
    Goods: false
  });

  const handleClick = (navElement) => {
    setIsOpen({
      Expertise: false,
      People: false,
      Goods: false,
      [navElement]: !isOpen[navElement]
    })
}

  const navElements = [
    {
      id: 1,
      name: "expertise",
      page: ""
    },
    {
      id: 2,
      name: "geople",
      page: "<PeoplePage />"
    },
    {
      id: 3,
      name: "goods",
      page: ""
    },
  ];

  return (
    <Fragment>
      <Head>
        <title>One Person Army</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.home}>

        <h1>Hello</h1>
        {/* <main className={styles.main}>
          {navElements.map((navElement) => (
            <AccordionItem 
              key={navElement.id} 
              navElement={navElement} 
              isOpen={isOpen}
              handleClick={handleClick}
            />
          ))}
        </main> */}
      </div>
    </Fragment>
  );
}
