import { useEffect, useRef } from "react";
import Head from "next/head";
import styles from "./people.module.css";
import SectionComponent from "@/components/section-component";

export default function PeoplePage() {
  const section1 = useRef();
  const section2 = useRef();
  const section3 = useRef();
  function scrollTo(section) {
    section.current.scrollIntoView({ behavior: "smooth" });
  }
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={`container ${styles.container}`}>
        <div ref={section1}>
          <SectionComponent
            image={`/images/austin-neill-Be7DMcK7k3o-unsplash.jpg`}
            headline={`Lorem Ipsum Dolor Sit Amet`}
            title={`Hello`}
            goToSectionRef={section2}
            scrollTo={scrollTo}
            showArrow={true}

          />
        </div>
        <div ref={section2}>
        <SectionComponent
            image={`/images/chris-chan-wA-dbT3FJnE-unsplash.jpg`}
            headline={`Lorem Ipsum Dolor Sit Amet`}
            title={`World`}
            goToSectionRef={section3}
            scrollTo={scrollTo}
            showArrow={true}
          />
        </div>
        <div ref={section3}>
        <SectionComponent
            image={`/images/michael-olsen--djS1aPrSr4-unsplash.jpg`}
            headline={`Lorem Ipsum Dolor Sit Amet`}
            title={`Test`}
            goToSectionRef={section1}
            scrollTo={scrollTo}
            showArrow={false}
          />
        </div>
      </div>
    </div>
  );
}